alphagov/backdrop

- backdrop/transformers/dispatch.py
- requirements.txt
- tests/transformers/test_dispatch.py
Default params are those of the parent. If it's realtime for instance
the transform target probably also needs to be realtime. The only
difference is the data_type and consequently the name (as this is auto
generated)
Relies on:
https://github.com/alphagov/performanceplatform-client.py/pull/43
> Create output dataset if missing using the api.

- README.md
- backdrop/core/query.py
- backdrop/core/storage/mongo.py
- backdrop/read/query.py
- backdrop/read/validation.py
- features/read_api/collect.feature
- features/read_api/combination_query.feature
- features/read_api/filter.feature
- features/read_api/group.feature
- tests/read/test_parse_request_args.py
- tests/read/test_validation.py
Add new filter_by_prefix parameter. This is similar to the existing
filter_by parameter, except that searches are anchored to the start of
the string.
The Mongo query is also constructed using 'find', but passed through as
{ 'pagePath': /^\\/housing-benefit.*/ } rather than { 'pagePath':
'/housing-benefit' }. Mongo will parse this as a regular expression
query.
We escape all strings passed into the filter using Python's re module.
The justification for this parameter is to support multi-part formats in
the info-frontend application - e.g. we would like to serve aggregate
statistics for the number of tickets submitted across all pages in
multi-part guides and smart answers. To do this with the existing
filter_by parameter would require a call to Backdrop for each page in
the guide or smart …
> Add filter_by_prefix parameter for regex support

- backdrop/read/api.py
- backdrop/transformers/dispatch.py
- backdrop/transformers/tasks/latest_dataset_value.py
- backdrop/transformers/tasks/rate.py
- backdrop/transformers/tasks/user_satisfaction.py
- requirements.txt
- tests/transformers/tasks/test_latest_data.py
- tests/transformers/tasks/test_rate.py
- tests/transformers/test_dispatch.py
This creates a transform task that is intended to be run when new data is written to backdrop which should be reflected in the services list (e.g. user satisfaction score).
We ensure that only "new" data is used to update the services list dataset. If data is being backfilled, old values could be written if this were not checked.
As this required some new data to be available to the transform task, the `compute` API has changed, and the tests for affected transforms updated.
> Services page data transform

- backdrop/transformers/tasks/latest_dataset_value.py
If specifying a start_at parameter, a request must also specify an end_at (or duration).
Since we want to retrieve the latest data, simply setting end_at to the current datetime is acceptable.
> Add end_at parameter to latest data task

- backdrop/transformers/tasks/latest_dataset_value.py
- tests/transformers/tasks/test_latest_data.py
The initial services page migration is effectively a backfill, which
this latest data check is supposed to prevent. Remove this until we have
run the migration when we can re instate
> Remove the restriction on latest data

- backdrop/transformers/tasks/latest_transaction_explorer_values.py
- tests/transformers/fixtures/transactions_explorer_example_data.json
- tests/transformers/tasks/test_latest_transaction_explorer_values.py
This ensures fixes small bugs with getting the latest transaction explorer data - when there is no dashboard for a service id and when data points are not present.
These second of these issues illustrates a problem however - should we fall back to earlier data if data is not present or null?
> Protect against empty dashboard list

- backdrop/transformers/tasks/latest_transaction_explorer_values.py
- tests/transformers/fixtures/transactions_explorer_example_data.json
- tests/transformers/tasks/test_latest_transaction_explorer_values.py
For some data points we are only interested in seasonally adjusted
data. This allows us to ignore data points with specified types meaning
that the latest data will always be of the correct type.
> Ignore data of specified types

- backdrop/transformers/tasks/latest_transaction_explorer_values.py
- tests/transformers/tasks/test_latest_transaction_explorer_values.py
Just using the first dashboard was used as a hack to get things working
and then forgotten about. Having been reminded by failures we now add
data for each dashboard.
Api has been tested and it always returns lists.
> Handle multiple data points for a service id.

- backdrop/transformers/tasks/latest_transaction_explorer_values.py
Previous filtering by dasboard slug means it will not post if there is
ANY newer data point for that dashboard. This made sense when we posted
all data from a time regardless of nulls and so the latest timestamp of
one data point was representative of the latest data point for all the
others. This is no longer true as we now post the latest non null for a
dashboard slug.
> Filter by id - there is > 1 data point per slug

- backdrop/transformers/tasks/user_satisfaction.py
- tests/transformers/tasks/test_user_satisfaction.py
Previously the transrom written daily by the update to customer
satisfaction datsets would cause an update to the latest period daily
until the period is complete. This mean periods without enough data for
a whole week being displayed on graphs and skewing this metric by
showing data supposedly for a week in the future.
We use end at to determine completeness as if data becomes more granular
in the future then the maximum _count may change.
> Ensure user sat records for incomplete periods not written

- tools/replicate-db.sh
The initial services page migration is effectively a backfill, which this
latest data check is supposed to prevent. Remove this until we have run the
migration when we can re instate. Also skip tests and fix a pep8 issue
> Migration script change directory rather than failing

- backdrop/transformers/dispatch.py
- tests/transformers/test_dispatch.py
Currently when a spreadsheet of data with timestamps between, say, the 26/02/2015 and
01/02/2015 this represents 7 days. However, the inferred start and end
ats inferred from this for the subsequent transform are the 26th to the
1st. As these are interpreted exclusively by backdrop it will only get 6
days of data back until the next upload. If the next upload contains the
data for this first week again and the next week - 02/02/2015 to
07/02/2015 it will then perform another exclusive query for the 26th to
the 7th. This time though it will include the FULL first week and update the
existing data accordingly, however the second week will again be one day
short. This ensures that dates passed through from
the write api are interpreted inclusively which seems like the expected
behaviour.
> Query for latest data inclusively.

- backdrop/core/validation.py
- tests/core/test_validation.py
When receiving a large amount of data, it can be helpful for a client
to know which record caused the problem.
Added after request from @benilovj.
> Add detail to error message

- backdrop/write/api.py
The smoke tests generate lots of log lines
with empty appends. To prevent this, don't
log audits of appending an empty dataset.
> Only audit log non-empty appends

- features/read_api/group.feature
This test has been failing for some time. Bisecting
the codebase to discover the commit responsible
hasn't turned anything up. Additionally, we are
reasonably sure that there are no longer any queries
that require grouping by this key.
Disabling the test temporarily will allow us
to test other changes and investigate with a
passing master branch.
> Skip organisation_acronym group_by test

- README.md
- tools/replicate-db.sh
As we move to gov.uk infrastructure, we will need to use the gov.uk dev vm
- allow this by passing govuk_dev as the destination host argument. Also
update the readme to be a little more verbose and include this argument.
> Allow syncing data to gov.uk dev vm

- backdrop/write/validation.py
- tests/write/test_flask_integration.py
Previously it was possible to pass this check when POSTing DELETEing etc
via the api and consquently make changes to data_sets without bearer
tokens. We do not have any of these in use however this is still a
problem.
> Check that the user has supplied a bearer token

- backdrop/transformers/tasks/latest_transaction_explorer_values.py
- tests/transformers/tasks/test_latest_transaction_explorer_values.py
In order to show as much data as possible
on the services page, we previously would
ignore later datapoints if the values were
None when creating the latest data dataset.
This modifies the transform to use the latest
datapoint, even if the value is None. This will
result in less data being shown on the services
page, but the data there will be fresher.
> Output latest data point even if None

- .travis.yml
By disabling sudo this lets travis use containers for faster builds.
> Disable sudo and cache pip -> enable containers

- backdrop/core/log_handler.py
- tests/core/test_json_logging.py
GOV.UK puppet will only pick up json logs when the path is
production.json.log not as it is at the moment.
> Json log should be at *.json.log not *.log.json

- start-app.sh
These stats are taking up approximately 80GB of disk space, because
each data group and type combination will create a new whisper file. We
dont need to know in this much detail how long the endpoints are taking
to respond
> Remove data group and type from statsd timer name

- backdrop/core/data_set.py
- tests/core/test_data_set.py
Slight differences in the way the _timestamp cell is formatted (in file uploads) 
results in duplicated data in the dataset.
What’s happening is this: _timestamp is listed as an auto_id for
the data set. All auto_id fields and values are joined together and
then base64 encoded and stored in the _id field.
AFTER the _id field has been created for the data record, the
_timestamp is parsed and converted to utc format. This means that
the date format of the timestamp can differ from the date format of
the timestamp in the _id.
The _id is used as a unique key for the data set.
The same _timestamp with a different date format will generate a
different _id value and will added as a new row in backdrop.
The fix was just to move converting the _timestamp to utc format
to BEFORE the base64 encoded …
> Format timestamp before creating id field

- backdrop/core/data_set.py
- tests/core/test_data_set.py
Reverts alphagov/backdrop#450
The fix we put in had an unintended side-effect. If users append new data to an existing spreadsheet, and then re-upload. As well as a new row being being created for the new data, new rows are created for the existing data. This is because the older data had primary keys containing timestamps in another date format, and this changed converts all timestamps to utc format before creating the primary key.
> Revert 6bbf31693cdda44e5ae49ccf02a10422564e4ee0

- backdrop/core/data_set.py
- backdrop/core/records.py
If the dataset pushed to backdrop contains any unicode characters,
a 500 error is returned to the user.
All of the top-level strings in the dataset have been encoded as utf-8
before continuing processing and validating of the dataset.
The check is limited to only the top-level strings in a dictionary
as currently all datasets pushed to backdrop are flat.
Pivotal: https://www.pivotaltracker.com/story/show/97119432 & https://www.pivotaltracker.com/story/show/94931202
> Encode unicode strings in dataset

- README.md
- backdrop/core/log_handler.py
- backdrop/transformers/config/development.py
The spike into Services page data anomalies (https://www.pivotaltracker.com/story/show/109073998) has uncovered that the configuration for transform in the development differs from that in preview, staging in production. This means that you can't just start backdrop and curl the transform end point update a transform data set.
In all of the other environments both backdrop write and transform use user backdrop_write and vhost /backdrop_write for the queue config.
In development, backdrop write uses user backdrop_write and vhost /backdrop_write for the queue config, but transforms uses user transformer and vhost /transformations.
To successfully trigger a transform in development with this set up I had to create the transformer user and /transformations vhost manually in rabbitmq.
To make …
> Change dev to match other envs

- backdrop/transformers/tasks/latest_dataset_value.py
- tests/transformers/tasks/test_latest_dataset_value.py
The import_dashboards.py script in Stagecraft (used for
importing Transactions Explorer data) expects to
find a service_id key in the service aggregates dataset.
This key was missed when this transform was produced and
is causing import_dashboards.py to fail.
> Add service_id to datasets of type latest_dataset_value

- backdrop/write/api.py
We made a change to allow the broker url to accept a list of rabbitmq
nodes. When node 1 was taken down, the celery process did not connect to
the next node in the list.
The default failover strategy for kombu is round-robin, but we
believe that celery is overwriting this and setting it to none if the
failover strategy is not explictly configured in the application
config.
> Set the celery failover strategy to round-robin

- tools/add_missing_service_id_key.js
This script will need to be manually copied to the primary performance mongo machine.
It is a run-once update.
> Add service_id to service_aggregates_latest_dataset_values if missing

- backdrop/core/records.py
- tests/core/test_data_set.py
Return a different error message for errors where the date is not a
date and for where the date is not a valid date.
> Return a more human friendly date error message

- tools/delete_empty_summary_records.js
Empty summary records are appearing in the transactional_services_summaries Mongo collection and are causing the transformation of these summary records into the service
aggregate records to fail.
We suspect the cause of these empty records are an empty row in a Google
spreadsheet which has been imported into the collection.
This script removes these empty records, which all have an empty service_id field.
> Data migration to remove empty summary records

- backdrop/core/data_set.py
- backdrop/core/storage/mongo.py
- backdrop/write/api.py
- tests/core/test_data_set.py
- tools/replicate-db.sh
Add a patch route to the Backdrop Write API to allow one or more values in a data set document to be updated e.g.
curl --request PATCH -H 'Content-type: application/json' -H 'Authorization: Bearer <bearer token>' http://10.1.1.254:3039/data/find-pension-contact-details/digital-take-up/<_id of document in a data set collection>' -d '{"count": 200}'
Multiple key-value pairs can be supplied via the -d argument
> Add patch to write api

- backdrop/core/log_handler.py
Currently, whilst deployed on PaaS the log files fill up until all
available space is used and then the app freezes.  This PR forces the
app to rotate log files every 10Mb with 5 backups.
This fixes #476 
It also excludes HEAD requests from logging output as the fastly ping will fill the logs very quickly
> Make sure log files are rotated
